..	|GH|	                replace:: *GitHub*
..	_GH:	                https://github.com/

..	_Git:	                https://git-scm.com/

..  |LPP|                   replace:: *Limited Pennyplane*

..  |MM|                    replace::   *Math-Magik*
..  _MM:                    https://github.com/rblack42/math-magik

..  |OSC|                   replace::   *OpenSCAD*
..  _OSC:                   https://openscad.org/

..  |STL|                   replace::    *STL*
..  _STL:                   https://en.wikipedia.org/wiki/STL_(file_format)

..	|PY|	                replace::	*Python*
..	_PY:	                https://www.python.org/

..  |RST|                   replace:: *reStructuredText*

..  _Sphinx:                https://www.sphinx-doc.org/en/master/

..  |AMA|                   replace:: *Academy of Model Aeronautics*
..  _AMA:                   https://www.modelaircraft.org/
..  _AMA Rulebook:          https://www.modelaircraft.org/sites/default/files/Indoor_Free_Flight_2019-2021.pdf

..  _Justin Lin:            https://openhome.cc/eGossip/OpenSCAD/FunctionGrapher.html

..  |TDD|                   replace::   *Test Driven Development*

..  _given when then:       https://martinfowler.com/bliki/GivenWhenThen.html

..  _semantic versioning:   https://semver.org/

..  _SymPy:                 https://www.sympy.org/en/index.html
